name: Azure Pipeline Deploy Stack

on:
  workflow_dispatch:

jobs:
  init:
    name: CI Workflow
    uses: codeparce/ci-workflows/.github/workflows/pipeline.node.swa.yml@v1
    with:
      cloud: azure
    secrets: inherit
      