name: Test Runner Docker

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: docker

    steps:
      - name: Test
        run: |
          echo "Runner funcionando"
          hostname
          whoami
          sleep 1000
