name: Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: kubernetes 

    steps:
      - name: Test
        run: |
          echo "Runner funcionando"
          hostname
          whoami
          
      - name: Mostrar variables
        run: |
          echo "Branch: $GITHUB_REF"
          echo "Branch corta: $GITHUB_REF_NAME"
          echo "Commit: $GITHUB_SHA"
          echo "Actor: $GITHUB_ACTOR"
          echo "Repo: $GITHUB_REPOSITORY"
          echo "Workflow: $GITHUB_WORKFLOW"
          echo "Run ID: $GITHUB_RUN_ID"
