name: On-Premise deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest #Runner cloud (default)
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Build in node
        uses: codeparce/ci-workflows/.github/actions/node/build@v1
        with:
          type: web-build
          target: dist

  docker-publish:
    needs: build
    runs-on: ubuntu-latest  #Runner cloud (default)
    steps:
      - uses: actions/checkout@v4
          
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: dist

      - name: Publish to Docker Hub
        uses: codeparce/ci-workflows/.github/actions/docker@v1
        with:
          docker-account-name: ${{ secrets.DOCKER_ACCOUNT_NAME }}
          docker-access-token: ${{ secrets.DOCKER_ACCESS_TOKEN }}


  deploy:
    runs-on: kubernetes #Runner on-premise
    needs: docker-publish
    env:
      GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Deploy to Kubernetes
        run: | 
          sudo apt update
          sudo apt-get install -y gettext

          cd kubernetes 
          set -a && source .env.kube && set +a

          envsubst < 1_namespace.template > 1_namespace.yaml
          envsubst < kustomization.template > kustomization.yaml
          envsubst < svc.template > svc.yaml
          envsubst < deployment.template > deployment.yaml
          envsubst < ingress.template > ingress.yaml

          kubectl apply -f ./

          echo "Domain: ${GITHUB_REPOSITORY_NAME}.${GITHUB_REF_NAME}.${NAME_SPACE}.lab"