on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest #Runner cloud (default)
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Build in node
        uses: codeparce/ci-workflows/.github/actions/node/build@v1
        with:
          type: web-build
          target: dist

  docker-publish:
    needs: build
    runs-on: ubuntu-latest  #Runner cloud (default)
    steps:
      - uses: actions/checkout@v4
          
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: dist

      - name: Publish to Docker Hub
        uses: codeparce/ci-workflows/.github/actions/docker@v1
        with:
          docker-account-name: ${{ secrets.DOCKER_ACCOUNT_NAME }}
          docker-access-token: ${{ secrets.DOCKER_ACCESS_TOKEN }}


  deploy:
    runs-on: kubernetes #Runner on-premise
    needs: docker-publish
    steps:
      - uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config
    
      - name: Deploy to Kubernetes
        run: | 
          ./kubernetes/deploy.sh